# Generated by Django 4.2.2 on 2023-08-05 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=200)),
                ('etopic', models.CharField(max_length=100)),
                ('ebanner', models.ImageField(null=True, upload_to='events/')),
                ('estatus', models.CharField(max_length=30)),
                ('eurl', models.URLField(max_length=255)),
                ('edate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimage', models.ImageField(null=True, upload_to='gallery/')),
                ('gdescription', models.CharField(max_length=150)),
                ('gyear', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, unique=True)),
                ('pwebsite', models.CharField(max_length=200, unique=True)),
                ('plogo', models.ImageField(null=True, upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tprofilepicture', models.ImageField(null=True, upload_to='team/')),
                ('tfullname', models.CharField(max_length=100)),
                ('tposition', models.CharField(max_length=50)),
                ('tlinkedin', models.CharField(max_length=20)),
                ('ttwitter', models.CharField(max_length=20)),
                ('tgithub', models.CharField(max_length=20)),
                ('taccademicyear', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
