# Generated by Django 4.2.2 on 2023-09-15 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=200)),
                ('etopic', models.CharField(max_length=100)),
                ('ebanner', models.ImageField(null=True, upload_to='events/')),
                ('estatus', models.CharField(max_length=30)),
                ('eurl', models.URLField(max_length=255)),
                ('edate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pavater', models.ImageField(null=True, upload_to='patron/')),
                ('Pname', models.CharField(max_length=100)),
                ('Pdesignation', models.CharField(max_length=300)),
            ],
        ),
    ]
