# Generated by Django 4.2.2 on 2023-10-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0002_members_patron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyucsa_id', models.CharField(max_length=10, unique=True)),
                ('student_no', models.CharField(max_length=15, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('program', models.CharField(max_length=30)),
                ('enrollment', models.DateField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='eslide',
            field=models.FileField(null=True, upload_to='eslides/'),
        ),
    ]
