# Generated by Django 4.2.2 on 2023-10-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0003_student_events_eslide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
