# Generated by Django 4.2.2 on 2023-10-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0004_rename_events_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
