# Generated by Django 4.2.2 on 2023-10-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0005_rename_members_member_rename_partners_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tfullname',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tposition',
            new_name='tpost',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tprofilepicture',
        ),
        migrations.AddField(
            model_name='team',
            name='tphoto',
            field=models.ImageField(default='team/avatar.png', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tgithub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tlinkedin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ttwitter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
