# Generated by Django 4.2.2 on 2023-11-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0006_rename_tfullname_team_tname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='program',
            new_name='programme',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_no',
            new_name='std_no',
        ),
    ]
