# Generated by Django 4.2.2 on 2023-11-10 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0009_studentregistration_technologies_delete_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='enrollmentYear',
            field=models.DateField(verbose_name=datetime.datetime(2023, 11, 10, 16, 52, 3, 339930)),
        ),
    ]
