# Generated by Django 4.2.2 on 2023-11-10 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0010_alter_studentregistration_enrollmentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='enrollmentYear',
            field=models.DateField(verbose_name=datetime.datetime(2023, 11, 10, 17, 22, 22, 651060)),
        ),
    ]
