# Generated by Django 4.2.2 on 2023-11-10 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0013_studentregistration_kyucsaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyucsaIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_id', models.PositiveIntegerField(default=70000000)),
            ],
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='kyucsaId',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='registeredAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
