# Generated by Django 4.2.2 on 2023-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0014_kyucsaidcounter_alter_studentregistration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='Padvice',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='Pdesignation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='Pname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tpost',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
