# Generated by Django 4.2.2 on 2023-11-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyucsa', '0015_patron_padvice_alter_patron_pdesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='Padvice',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='Pname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
