# Generated by Django 4.2.2 on 2024-04-18 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=200)),
                ('etopic', models.CharField(max_length=100)),
                ('ebanner', models.ImageField(null=True, upload_to='events/')),
                ('eslide', models.FileField(null=True, upload_to='eslides/')),
                ('estatus', models.CharField(max_length=30)),
                ('eurl', models.URLField(max_length=255)),
                ('edate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimage', models.ImageField(null=True, upload_to='gallery/')),
                ('gdescription', models.CharField(max_length=150)),
                ('gyear', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KyucsaIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_id', models.PositiveIntegerField(default=70000000)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, unique=True)),
                ('pwebsite', models.CharField(max_length=200, unique=True)),
                ('plogo', models.ImageField(null=True, upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pavater', models.ImageField(null=True, upload_to='patron/')),
                ('Pname', models.CharField(max_length=50, null=True)),
                ('Pdesignation', models.CharField(max_length=50, null=True)),
                ('Padvice', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('kyucsaId', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('programme', models.CharField(choices=[('Choose', 'Choose...'), ('BITC', 'BITC'), ('BIS', 'BIS'), ('BLIS', 'BLIS')], default='Choose', max_length=15)),
                ('gender', models.CharField(choices=[('Choose', 'Choose...'), ('M', 'Male'), ('F', 'Female')], default='Choose', max_length=10)),
                ('academicStatus', models.CharField(choices=[('Choose', 'Choose...'), ('Continuing', 'Continuing'), ('Graduated', 'Graduated')], default='Choose', max_length=20)),
                ('studentNumber', models.IntegerField()),
                ('enrollmentYear', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024)),
                ('email', models.EmailField(max_length=30)),
                ('mobileNumber', models.IntegerField()),
                ('registeredAt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tphoto', models.ImageField(default='team/avatar.png', null=True, upload_to='team/')),
                ('tname', models.CharField(max_length=100, null=True)),
                ('tpost', models.CharField(max_length=50, null=True)),
                ('ttwitter', models.CharField(max_length=20, null=True)),
                ('tgithub', models.CharField(max_length=20, null=True)),
                ('tlinkedin', models.CharField(max_length=20, null=True)),
                ('taccademicyear', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tTitle', models.CharField(max_length=200)),
                ('tDescription', models.CharField(max_length=300)),
                ('tPhoto', models.ImageField(null=True, upload_to='technologies/')),
                ('tUrl', models.URLField(max_length=255)),
            ],
        ),
    ]
